[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = ["dnas/*/zomes/coordinator/*", "dnas/*/zomes/integrity/*"]
resolver = "2"

[workspace.dependencies]
hdi = "=0.6.3"
hdk = "=0.5.3"
serde = "1.0"
rand = "0.8.5"
holochain_serialized_bytes = "*"

[workspace.dependencies.dino_adventure]
path = "dnas/dino_adventure/zomes/coordinator/dino_adventure"

[workspace.dependencies.dino_adventure_integrity]
path = "dnas/dino_adventure/zomes/integrity/dino_adventure"
