name: "test"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          install_url: https://releases.nixos.org/nix/nix-2.28.3/install

      - uses: cachix/cachix-action@v16
        with:
          name: holochain-ci

      - uses: Swatinem/rust-cache@v2

      - name: Install dependencies
        run: |
          nix develop --command bash -c "npm ci"

      - name: Lint
        run: |
          nix develop --command bash -c "npm run lint"

      - name: Test
        run: |
          nix develop --command bash -c "npm test"
  ci_pass:
    if: ${{ always() }}
    runs-on: "ubuntu-latest"
    needs:
      - test
    steps:
      - name: check status
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
